# Generated by Django 4.2.6 on 2023-10-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('branch', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('is_verifyed', models.BooleanField(default=False)),
                ('is_email_verifyed', models.BooleanField(default=False)),
                ('is_onboarded', models.BooleanField(default=False)),
                ('is_male', models.BooleanField(default=False)),
                ('ip', models.CharField(blank=True, max_length=50)),
                ('profile_image', models.FileField(blank=True, upload_to=None)),
                ('bio', models.TextField(blank=True)),
                ('college', models.CharField(blank=True, max_length=100)),
                ('college_entry', models.DateTimeField(blank=True, null=True)),
                ('rank', models.PositiveIntegerField(default=1)),
                ('created_branches', models.ManyToManyField(blank=True, related_name='created_branches', to='branch.branch')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('saved_branchs', models.ManyToManyField(blank=True, related_name='saved_branch', to='branch.branch')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('viewed_branches', models.ManyToManyField(blank=True, related_name='viewed_branches', to='branch.branch')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
